name: Release

on:
    push:
        branches:
            - main

jobs:
    standard-version:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - uses: actions/setup-node@v3

            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Print versions
              run: |
                  git --version
                  node --version
                  npm --version
                  npx commitlint --version

            - name: Standard version
              run: |
                  npm ci
                  git config user.name "github-actions[bot]"
                  git config user.email "<>"
                  npx standard-version
                  git push --follow-tags origin $GITHUB_REF_NAME
